 else if(stage==='review'){body=`<div class="review-stack"><div class="effective-card"><span class="eyebrow">COMPLIANCE CONSEQUENCE</span><strong>COUNTRY RESTRICTION WILL BE REMOVED</strong><p>Contact permission is not assumed. Master DNC will recalculate every affected record against the remaining restrictions.</p></div><div class="review-card"><h3>Removal summary</h3><dl><div><dt>Countries</dt><dd>${count}</dd></div><div><dt>Reason</dt><dd>${esc(state.rlcRemoveReason)}</dd></div></dl></div><div class="review-card"><h3>Broadcast scope</h3><div class="scope-grid"><span>RLC directory</span><span>Effective status engine</span><span>Search and suppression controls</span><span>External compliance sync</span></div></div></div>`;footer=`${button('Back','secondary','data-action="rlc-remove-back"')}${button('Remove & Broadcast','primary','data-action="rlc-remove-to-confirm"')}`;}
 else if(stage==='broadcast-confirm'){body=`<div class="review-stack"><div class="inline-alert inline-alert-warning"><div class="inline-alert-title">Confirm organisation-wide broadcast</div>The RLC database change and its propagation are tracked as separate auditable operations. Confirming will update all connected compliance workflows.</div><div class="review-card"><h3>Broadcast confirmation</h3><p>${count} countr${count===1?'y':'ies'} will be removed and the change will be sent to four connected compliance systems.</p></div></div>`;footer=`${button('Back','secondary','data-action="rlc-confirm-back"')}${button('Confirm Broadcast','primary','data-action="rlc-remove-confirm"')}`;}
 else {const systems=['RLC directory','Effective status engine','Contact suppression controls','External compliance sync'];body=`<div class="processing-stack"><div class="inline-alert inline-alert-${stage==='success'?'success':'info'}"><div class="inline-alert-title">${stage==='success'?'RLC removal complete':'Broadcasting RLC change'}</div>${stage==='success'?'The selected country restrictions were removed and all connected systems were updated.':'The RLC database change is recorded. Connected compliance workflows are now being updated.'}</div><div class="system-card">${systems.map((x,i)=>{const done=stage==='success'||state.rlcRemoveProgress>i,active=stage==='processing'&&state.rlcRemoveProgress===i;return `<div class="system-row"><span>${x}</span><span class="system-status ${done?'system-complete':active?'system-active':''}">${done?'Updated':active?'Updating…':'Pending'}</span></div>`}).join('')}</div></div>`;footer=stage==='success'?button('Done','primary','data-action="rlc-remove-done"'):button('Broadcasting…','primary','disabled');}
 return `<div class="modal-layer" role="dialog" aria-modal="true" aria-label="RLC removal workflow"><button class="modal-scrim" data-action="rlc-remove-close"></button><div class="restriction-modal"><div class="restriction-modal-header"><div class="modal-title-row"><div><h2>${stage==='reason'?'Remove from RLC':stage==='review'?'Review removal':stage==='broadcast-confirm'?'Confirm Broadcast':stage==='success'?'Removal complete':'Broadcasting change'}</h2><p>${stage==='reason'?'Provide an auditable reason before changing country-level policy.':stage==='review'?'Review the compliance consequence before the database change.':stage==='broadcast-confirm'?'Broadcast is a separate organisation-wide action.':'Connected compliance systems are updating.'}</p></div><button class="icon-button" data-action="rlc-remove-close">${icon('x')}</button></div></div><div class="restriction-modal-body">${body}</div><div class="restriction-modal-footer">${footer}</div></div></div>`;}
async function runRlcRemoval(){state.rlcRemoveStage='processing';state.rlcRemoveProgress=0;render();for(let i=1;i<=4;i++){await new Promise(r=>setTimeout(r,420));state.rlcRemoveProgress=i;render();}await new Promise(r=>setTimeout(r,280));state.rlcRemoveStage='success';render();}
function finishRlcRemoval(){const ids=new Set(state.rlcSelected);state.rlcRecords=state.rlcRecords.filter(r=>!ids.has(r.id));state.rlcSelected=new Set();state.rlcRemoveStage=null;state.toast=`${ids.size} RLC countr${ids.size===1?'y':'ies'} removed and broadcast successfully.`;render();}
function viewHash(v){return v==='overview'?'':`#${v}`;}
function render(){const views={overview,cdnc,idnc,blacklist,audit,'bulk-import':bulkImport,'broadcast-queue':broadcastQueue,concurrent,rlc};document.getElementById('app').innerHTML=(views[state.view]||overview)();}
async function runSearch(q=state.query){state.searchLoading=true;state.searchError=false;state.submittedQuery=q;state.correction='';state.matchLogic='';state.page=1;state.selected=new Set();state.allMatching=false;render();await new Promise(r=>setTimeout(r,650));const n=q.trim().toLowerCase();if(n==='error'||n==='network error'){state.searchLoading=false;state.searchError=true;render();return;}let eff=n;if(['flip cart','flipkartt','flip-kart'].includes(n)){eff='flipkart';state.correction='Flipkart'}state.records=!eff?state.liveRecords:state.liveRecords.filter(r=>`${r.company} ${r.domain} ${r.website} ${r.sector} ${r.aliases.join(' ')}`.toLowerCase().includes(eff));state.matchLogic=eff?'Showing the most relevant matches across company name, domain and keywords.':'';state.searchLoading=false;render();}
function clearSearch(){Object.assign(state,{query:'',submittedQuery:'',records:state.liveRecords,searchError:false,correction:'',matchLogic:'',page:1,status:'All statuses',sector:'All sectors',selected:new Set(),allMatching:false});render();}
function openModal(type, subtype=null){state.addType=type;state.addSubtype=subtype;state.addOrigin=state.view;state.addStage='form';state.addProgress=0;state.modalCompany=type==='RLC'?'Iran':type==='CDNC'?'':'Aarav Mehta';state.modalDomain='';state.modalReason='';state.addErrors={};state.addMenu=false;state.announcement=`Add ${subtype?`${subtype} `:''}${type} restriction dialog opened.`;render();setTimeout(()=>document.querySelector('.restriction-modal input, .restriction-modal select, .restriction-modal textarea')?.focus(),0);}
async function modalContinue(){if(state.addStage==='duplicate')return;const errors={};if(!(state.modalCompany||'').trim())errors.company='This field is required.';if(state.addType==='CDNC'&&state.modalDomain&&!state.modalDomain.includes('.'))errors.domain='Enter a valid company domain.';if(!(state.modalReason||'').trim())errors.reason='Reason for restriction is required.';state.addErrors=errors;if(Object.keys(errors).length){render();return;}state.addStage='checking';render();await new Promise(r=>setTimeout(r,850));const dup=`${state.modalCompany||''} ${state.modalDomain||''}`.toLowerCase().includes('flipkart');state.addStage=dup?'duplicate':'review';render();}
async function broadcast(){state.addStage='processing';state.addProgress=0;render();for(let i=1;i<=4;i++){await new Promise(r=>setTimeout(r,450));state.addProgress=i;render();}await new Promise(r=>setTimeout(r,350));state.addStage='success';render();}
function startRemoval(context){state.removeContext=context||'CDNC';const has=state.removeContext==='CDNC'?(state.selected.size||state.allMatching):state.removeContext.startsWith('IDNC')?(state.personSelected?.size||state.personAllMatching):(state.blacklistSelected?.size||state.blacklistAllMatching);if(!has)return;state.removeStage='reason';state.removeReason='';state.removeError='';state.removeProgress=0;render();}
async function runRemoval(){state.removeStage='processing';state.removeProgress=0;render();for(let i=1;i<=4;i++){await new Promise(r=>setTimeout(r,420));state.removeProgress=i;render();}await new Promise(r=>setTimeout(r,300));state.removeStage='success';render();}
