Removal(){state.rlcRemoveStage='processing';state.rlcRemoveProgress=0;render();for(let i=1;i<=4;i++){await new Promise(r=>setTimeout(r,420));state.rlcRemoveProgress=i;render();}await new Promise(r=>setTimeout(r,280));state.rlcRemoveStage='success';render();}
function finishRlcRemoval(){const ids=new Set(state.rlcSelected);state.rlcRecords=state.rlcRecords.filter(r=>!ids.has(r.id));state.rlcSelected=new Set();state.rlcRemoveStage=null;state.toast=`${ids.size} RLC countr${ids.size===1?'y':'ies'} removed and broadcast successfully.`;render();}

function recordDetailModal(){
 const r=state.recordDetail; if(!r)return '';
 const other=r.company==='Flipkart'?['Blacklist: related legal entity','IDNC Expert: one active contact']:['No additional restrictions found in this mock example'];
 return `<div class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="record-detail-title"><button class="modal-scrim" aria-label="Close record details" data-action="record-detail-close"></button><div class="restriction-modal detail-modal"><div class="restriction-modal-header"><div class="modal-title-row"><div><h2 id="record-detail-title">${esc(r.company)}</h2><p>${esc(r.domain)} · CDNC restriction record</p></div><button class="icon-button" aria-label="Close" data-action="record-detail-close">${icon('x')}</button></div></div><div class="restriction-modal-body"><div class="review-stack"><div class="effective-card"><span class="eyebrow">EFFECTIVE CONTACT STATUS</span><strong>DO NOT CONTACT</strong><p>Master DNC determines this from all active restrictions. Removing this CDNC entry would trigger recalculation, not automatic contact permission.</p></div><div class="detail-grid"><div class="detail-kv"><span>Status</span><strong>${esc(r.status)}</strong></div><div class="detail-kv"><span>Sector</span><strong>${esc(r.sector)}</strong></div><div class="detail-kv"><span>Domain</span><strong>${esc(r.domain)}</strong></div><div class="detail-kv"><span>Last updated</span><strong>14 Aug, 12:42</strong></div></div><div class="review-card"><h3>Other relevant restrictions</h3>${other.map(x=>`<p>${esc(x)}</p>`).join('')}</div><div class="review-card"><h3>Audit history</h3><div class="timeline-list"><div class="timeline-row"><strong>14 Aug, 12:42</strong><span>Restriction reviewed</span><span>Vaibhav Sharma</span></div><div class="timeline-row"><strong>12 Aug, 16:08</strong><span>External sync retried</span><span>Riya Kapoor</span></div><div class="timeline-row"><strong>08 Aug, 10:14</strong><span>Record created</span><span>Compliance Team</span></div></div></div>${state.role==='View only'?`<div class="inline-alert inline-alert-info"><div class="inline-alert-title">View-only access</div>You can review this record, but only Compliance Administrators can remove it.</div>`:''}</div></div><div class="restriction-modal-footer">${button('Close','secondary','data-action="record-detail-close"')}${state.role==='View only'?'':button('Remove restriction','primary','data-action="record-detail-remove"')}</div></div></div>`;
}
function auditPreviewModal(){
 const r=state.auditPreview; if(!r)return '';
 return `<div class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="audit-preview-title"><button class="modal-scrim" aria-label="Close audit event" data-action="audit-preview-close"></button><div class="restriction-modal detail-modal"><div class="restriction-modal-header"><div class="modal-title-row"><div><h2 id="audit-preview-title">Audit event</h2><p>Immutable event ${esc(r.id.toUpperCase())}</p></div><button class="icon-button" aria-label="Close" data-action="audit-preview-close">${icon('x')}</button></div></div><div class="restriction-modal-body"><div class="review-stack"><div class="detail-grid"><div class="detail-kv"><span>Time</span><strong>${esc(r.time)}</strong></div><div class="detail-kv"><span>Action</span><strong>${esc(r.activity)}</strong></div><div class="detail-kv"><span>Record</span><strong>${esc(r.record)}</strong></div><div class="detail-kv"><span>DNC type</span><strong>${esc(r.type)}</strong></div><div class="detail-kv"><span>Performed by</span><strong>${esc(r.owner)}</strong></div><div class="detail-kv"><span>Outcome</span><strong>${esc(r.status)}</strong></div></div><div class="review-card"><h3>Change evidence</h3><p>This preview documents what changed and who performed it. Audit history is immutable and cannot be edited from this screen.</p><div class="upload-box"><span>${icon('upload',20)}</span><div><strong>compliance-evidence.pdf</strong><span>Evidence snapshot attached to this mock audit event</span></div>${button('Preview document','text','data-action="audit-document-preview"')}</div></div>${state.auditDocumentPreview?`<div class="review-card"><h3>Document preview</h3><div style="height:180px;border:1px solid var(--border);border-radius:8px;background:#f8fafb;display:grid;place-items:center;text-align:center;padding:24px"><div><strong>Compliance Evidence</strong><p class="results-logic">Read-only document preview. Original evidence remains unchanged.</p></div></div></div>`:''}</div></div><div class="restriction-modal-footer">${button('Close','primary','data-action="audit-preview-close"')}</div></div></div>`;
}
function queueDetailModal(){
 const key=state.queueDetail;if(!key)return '';
 const data=key==='remove-cdnc'?['Remove 18 CDNC records','CDNC','External compliance sync']:key==='add-expert'?['Add expert restriction','IDNC Expert','Processing']:['Remove blacklist record','Blacklist','Queued'];
 return `<div class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="queue-detail-title"><button class="modal-scrim" aria-label="Close broadcast details" data-action="queue-detail-close"></button><div class="restriction-modal detail-modal"><div class="restriction-modal-header"><div class="modal-title-row"><div><h2 id="queue-detail-title">Broadcast details</h2><p>${esc(data[0])}</p></div><button class="icon-button" data-action="queue-detail-close">${icon('x')}</button></div></div><div class="restriction-modal-body"><div class="review-stack"><div class="review-card"><h3>Operation</h3><div class="detail-grid"><div class="detail-kv"><span>DNC type</span><strong>${esc(data[1])}</strong></div><div class="detail-kv"><span>Requested by</span><strong>Vaibhav Sharma</strong></div></div></div><div class="review-card"><h3>Connected systems</h3><div class="broadcast-detail-list"><div class="broadcast-detail-row"><span>DNC directory</span><strong>Updated</strong></div><div class="broadcast-detail-row"><span>Effective status</span><strong>Updated</strong></div><div class="broadcast-detail-row"><span>Contact suppression controls</span><strong>Updated</strong></div><div class="broadcast-detail-row"><span>External compliance sync</span><strong>${esc(data[2])}</strong></div></div></div><div class="inline-alert inline-alert-info"><div class="inline-alert-title">Retry behavior</div>If a downstream operation fails, only that failed operation is retried. Successful updates remain preserved.</div></div></div><div class="restriction-modal-footer">${button('Close','primary','data-action="queue-detail-close"')}</div></div></div>`;
}
function viewHash(v){return v==='overview'?'':`#${v}`;}
function render(){const views={overview,cdnc,idnc,blacklist,audit,'bulk-import':bulkImport,'broadcast-queue':broadcastQueue,concurrent,rlc};document.getElementById('app').innerHTML=(views[state.view]||overview)();}
async function runSearch(q=state.query){state.searchLoading=true;state.searchError=false;state.submittedQuery=q;state.correction='';state.matchLogic='';state.page=1;state.selected=new Set();state.allMatching=false;render();await new Promise(r=>setTimeout(r,650));const n=q.trim().toLowerCase();if(n==='error'||n==='network error'){state.searchLoading=false;state.searchError=true;render();return;}let eff=n;if(['flip cart','flipkartt','flip-kart'].includes(n)){eff='flipkart';state.correction='Flipkart'}state.records=!eff?state.liveRecords:state.liveRecords.filter(r=>`${r.company} ${r.domain} ${r.website} ${r.sector} ${r.aliases.join(' ')}`.toLowerCase().includes(eff));state.matchLogic=eff?'Showing the most relevant matches across company name, domain and keywords.':'';state.searchLoading=false;render();}
function clearSearch(){Object.assign(state,{query:'',submittedQuery:'',records:state.liveRecords,searchError:false,correction:'',matchLogic:'',page:1,status:'All statuses',sector:'All sectors',selected:new Set(),allMatching:false});render();}
function openModal(type, subtype=null){state.addType=type;state.addSubtype=subtype;state.addOrigin=state.view;state.addStage=state.role==='View only'?'permission':'form';state.addProgress=0;state.modalCompany=type==='RLC'?'':type==='CDNC'?'':'Aarav Mehta';state.modalDomain='';state.modalReason='';state.addErrors={};state.addMenu=false;state.announcement=`Add ${subtype?`${subtype} `:''}${type} restriction dialog opened.`;render();setTimeout(()=>document.querySelector('.restriction-modal input, .restriction-modal select, .restriction-modal textarea')?.focus(),0);}
async function modalContinue(){if(['duplicate','possible-duplicate'].includes(state.addStage))return;const errors={};if(!(state.modalCompany||'').trim())errors.company='This field is required.';if(state.addType==='CDNC'&&(!(state.modalDomain||'').trim()||!state.modalDomain.includes('.')))errors.domain='Enter a valid company domain.';if(state.addType==='RLC'&&state.modalReference&&!/^https?:\/\//i.test(state.modalReference))errors.reference='Enter a valid https:// reference URL.';if(!(state.modalReason||'').trim())errors.reason='Reason for restriction is required.';state.addErrors=errors;if(Object.keys(errors).length){render();return;}state.addStage='checking';render();await new Promise(r=>setTimeout(r,700));const text=`${state.modalCompany||''} ${state.modalDomain||''}`.toLowerCase();const exact=text.includes('flipkart')||state.addType==='RLC'&&['iran','north korea','syria'].includes((state.modalCompany||'').trim().toLowerCase())||state.addType==='IDNC'&&['aarav mehta','riya kapoor'].includes((state.modalCompany||'').trim().toLowerCase());const possible=text.includes('flip cart')||text.includes('flpkart')||text.includes('possible');if(exact){state.addStage='duplicate';render();return;}if(possible){state.addStage='possible-duplicate';render();return;}state.crossListReason='';const name=(state.modalCompany||'').toLowerCase();if(name.includes('neha')||name.includes('iran')||name.includes('dprk'))state.crossListReason='Blacklist and RLC restrictions are already active for related entities.';state.addStage='review';render();}
async function broadcast(){state.addStage='processing';state.addProgress=0;state.partialDetails=false;render();for(let i=1;i<=4;i++){await new Promise(r=>setTimeout(r,350));state.addProgress=i;render();}await new Promise(r=>setTimeout(r,250));const partial=(state.modalReason||'').toLowerCase().includes('partial')&&!state.partialRetried;state.addStage=partial?'partial':'success';render();}
async function retryModalFailed(){state.addStage='processing';state.addProgress=3;state.partialRetried=true;state.announcement='Retrying failed external compliance sync only.';render();await new Promise(r=>setTimeout(r,800));state.addProgress=4;state.addStage='success';state.announcement='Failed external compliance sync retried successfully.';render();}
function startRemoval(context){state.removeContext=context||'CDNC';const 